<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Written by Jeff Paranich jeffrey@ieee.org -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>sno</string>
    <string>sbl</string>
   </array>
  <key>name</key>
  <string>spitbol</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.spitbol</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(^\*.*)</string>
          <key>name</key>
          <string>comment.spitbol</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(^[A-Z0-9a-z._]+)</string>
          <key>name</key>
          <string>keyword.spitbol</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&amp;ABEND|&amp;ANCHOR|&amp;CASE|&amp;CODE|&amp;COMPARE|&amp;DUMP|&amp;ERRLIMIT|&amp;ERRTEXT|&amp;ERRTPE|&amp;FTRACE|&amp;FULLSCAN|&amp;INPUT|&amp;MAXLNGTH|&amp;OUTPUT|&amp;STLIMIT|&amp;PROFILE|&amp;TRACE|&amp;TRIM)</string>
          <key>name</key>
          <string>entity.name.tag.css.spitbol</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&amp;ABORT|&amp;ALPHABET|&amp;ARB|&amp;BAL|&amp;ERRTEXT|&amp;ERRTYPE|&amp;FAIL|&amp;FENCE|&amp;FILE|&amp;FNCLEVEL|&amp;LASTFILE|&amp;LASTLINE|&amp;LASTNO|&amp;LCASE|&amp;LINE|&amp;PARM|&amp;REM|&amp;RTNTYPE|&amp;STCOUNT|&amp;STFCOUNT|&amp;STNO|&amp;SUCCEED|&amp;UCASE|&amp;ANCHOR|&amp;CASE|&amp;CODE|&amp;DUMP|&amp;ERRLIMIT|&amp;FTRACE|&amp;FULLSCAN|&amp;INPUT|&amp;MAXLNGTH|&amp;OUTPUT|&amp;STLIMIT|&amp;TRACE|&amp;TRIM)</string>
          <key>name</key>
          <string>entity.name.tag.css.spitbol</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\t\s\x{003d}]ABORT[\t\s\x{003d}]|[\t\s\x{003d}]CONTINUE[\t\s\x{003d}]|[\t\s\x{003d}]END[\t\s\x{003d}]|[\t\s\x{003d}]FRETURN[\t\s\x{003d}]|[\t\s\x{003d}]INPUT[\t\s\x{003d}]|[\t\s\x{003d}]NRETURN[\t\s\x{003d}]|[\t\s\x{003d}]OUTPUT[\t\s\x{003d}]|[\t\s\x{003d}]RETURN[\t\s\x{003d}]|[\t\s\x{003d}]SCONTINUE[\t\s\x{003d}]|[\t\s\x{003d}]TERMINAL[\t\s\x{003d}]|[\t\s\x{003d}]PUNCH[\t\s\x{003d}])</string>
          <key>name</key>
          <string>entity.other.attribute-name.spitbol</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((APPLY|ARRAY|CONVERT|ENDFILE|FENCE|HOST|ITEM|ITEM|PROTOTYPE|RSORT|RSORT|SORT|SORT|TABLE|EVAL|CODE|APPLY|ARG|DEFINE|LOAD|LOCAL|OPSYN|UNLOAD|BACKSPACE|DETACH|EJECT|ENDFILE|INPUT|OUTPUT|REWIND|SET|CLEAR|COLLECT|DUMP|CHAR|CONVERT|DATATYPE|DATE|EVAL|SIZE|TIME|ATAN|CHOP|COS|EXP|LN|REMDR|SIN|SQRT|TAN|EQ|GE|GT|INTEGER|LE|LT|NE|DIFFER|IDENT|COPY|DUPL|ANY|ARBNO|BREAK|BREAKX|FENCE|LEN|NOTANY|POS|RPOS|RTAB|SPAN|TAB|EXIT|EXIT|HOST|SETEXIT|STOPTR|TRACE|DATA|FIELD|DATATYPE|LEQ|LGE|LGT|LLE|LLT|LNE|DUPL|LPAD|REPLACE|REVERSE|REWIND|RSORT|SORT|SETEXIT|RPAD|SUBSTR|TRIM))</string>
          <key>name</key>
          <string>markup.deleted.spitbol</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(:s\(|:\(|:S\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.spitbol</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>keyword.spitbol</string>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.spitbol</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(:f\(|:F\(|F\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>invalid.spitbol</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>keyword.spitbol</string>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>invalid.spitbol</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.css.spitbol</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>emphasis.spitbol</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.css.spitbol</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.css.spitbol</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>emphasis.spitbol</string>
          <key>end</key>
          <string>(\&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.css.spitbol</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\*|\+|-|/|\^|\*\*|!)</string>
          <key>name</key>
          <string>constant.numeric.spitbol</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(=)</string>
          <key>name</key>
          <string>constant.language.spitbol</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\(|\)|,|\||&lt;|&gt;)</string>
          <key>name</key>
          <string>entity.name.tag.css.spitbol</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([0-9])</string>
          <key>name</key>
          <string>meta.embedded.spitbol</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\s\.\s|\s\?\s)</string>
          <key>name</key>
          <string>string.regexp.spitbol</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Z0-9a-z._]+)</string>
          <key>name</key>
          <string>meta.embedded.spitbol</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
  </dict>
</dict>
</plist>
